- README.md
- SUPPORT.md
DO NOT MERGE before the new roadmap pages are published.
> WIP: update roadmap link

- knowledge-base/examples/treeview/treeview-adding-nodes/main.jsx
- knowledge-base/treeview-add-items-dynamically.md
> TreeView KB for dynamically adding child nodes

- knowledge-base/examples/grid/grid-save-datastate-to-localstorage/main.jsx
- knowledge-base/grid-store-state-in-localstorage.md
Related to [https://github.com/telerik/kendo-react-private/issues/2405](https://github.com/telerik/kendo-react-private/issues/2405)
> Grid Preserve State on Refresh KB Article

- knowledge-base/examples/rangleslider/main.jsx
- knowledge-base/rangeslider-slider-dots-title.md
Related to [https://github.com/telerik/kendo-react-private/issues/2404](https://github.com/telerik/kendo-react-private/issues/2404)
> RangeSlider Set Dots' Title To Dragged Value KB

- knowledge-base/examples/grid/auto-width/canvas/main.jsx
> Add cell padding to the column width calculation

- knowledge-base/examples/grid/grid-whitespace-textoverflow/CSS/main.jsx
- knowledge-base/examples/grid/grid-whitespace-textoverflow/cell/main.jsx
- knowledge-base/examples/grid/grid-whitespace-textoverflow/cellRender/main.jsx
- knowledge-base/examples/grid/grid-whitespace-textoverflow/shared/products.json
- knowledge-base/grid-cell-whitespace-textoverflow.md
Related to [#2143](https://github.com/telerik/kendo-react-private/issues/2413)
> KB for removing the wrapping and ellipsis of the Grid cells

- knowledge-base/examples/listbox/listbox-keyboard-navigation/main.jsx
- knowledge-base/listbox-keyboard-navigation.md
Related to [https://github.com/telerik/kendo-react-private/issues/2441](https://github.com/telerik/kendo-react-private/issues/2441)
> ListBox Keyboard Navigation KB article

- knowledge-base/examples/grid/excel-export-parent-child/main.jsx
Comment:
Use functional component instead
> [FeedBack] - convert class demo to functional

- knowledge-base/daterangepicker-predefined-ranges.md
Currently, the demo example is not rendered properly due to the missing id.
> Fixing the demo

- knowledge-base/examples/grid/grid-cell-state-editing/main.jsx
- knowledge-base/examples/grid/grid-cell-state-editing/products.jsx
- knowledge-base/grid-cell-state-editing.md
> add grid edit demo with stateful cells

- knowledge-base/examples/popup/close-on-click-outside/main.jsx
This fixes the opening and closing issue when opening the Popup.
Closes https://github.com/telerik/kendo-react-private/issues/2499
> fix open and close issue

- knowledge-base/daterangepicker-error-message-invalid-date.md
- knowledge-base/examples/dropdowns/daterangepicker-validation/customEndDateInput.jsx
- knowledge-base/examples/dropdowns/daterangepicker-validation/customStartDateInput.jsx
- knowledge-base/examples/dropdowns/daterangepicker-validation/main.jsx
- knowledge-base/examples/grid/grid-disable-reodering/main.jsx
- knowledge-base/examples/multiselecttree/multiselecttree-lazy-loading/main.jsx
- knowledge-base/examples/multiselecttree/multiselecttree-lazy-loading/multiselecttree-data-operations.js
- knowledge-base/examples/multiselecttree/multiselecttree-lazy-loading/style.css
- knowledge-base/examples/multiselecttree/multiselecttree-lazy-loading/tree-data.js
- knowledge-base/grid-disable-reordering.md
- knowledge-base/multiselecttree-lazy-loading.md
Related to https://github.com/telerik/kendo-react-private/issues/3121
> October 2023 KB articles

- knowledge-base/examples/grid/checkboxfilter-outside-grid/columnMenu.jsx
- knowledge-base/examples/grid/checkboxfilter-outside-grid/main.jsx
- knowledge-base/examples/grid/grid-csv-export/main.jsx
- knowledge-base/examples/multiselect/multiselect-tags-and-tagrender/main.jsx
- knowledge-base/grid-export-csv.md
- knowledge-base/gridcolumnmenucheckboxfilter-outside-grid.md
- knowledge-base/multiselect-tags-and-tagrender.md
Related to https://github.com/telerik/kendo-react-private/issues/3198
> Three KB articles for the Grid and MultiSelect component

- knowledge-base/examples/grid/grid-selection-mobile-scrolling/main.jsx
- knowledge-base/grid-selection-mobile-scrolling.md
Related to https://github.com/telerik/kendo-react-private/issues/3334
> docs(grid): selection with mobile scrolling kb

- examples/kendo-react-nextjs/app/components/grid/interfaces.ts
- examples/kendo-react-nextjs/app/components/grid/main.tsx
- Fixed types in the Order interface:
- orderDate
- requiredDate
- shippedDate
- Fixed type in the OrderShipAdress interface:
- postalCode
> chore: fixed type error

- examples/kendo-react-nodejs-express/.gitignore
- examples/kendo-react-nodejs-express/client/package-lock.json
- examples/kendo-react-nodejs-express/server/package-lock.json
- examples/kendo-react-stackblitz-app/package-lock.json
- examples/react-admin-dashboard/package-lock.json
- examples/react-admin-dashboard/src/components/dashboard/Alert.jsx
- examples/react-admin-dashboard/src/pages/About.jsx
- Added necessary package-lock files for CI in:
- kendo-react-file-manager
- kendo-react-nodejs-express
- kendo-react-stackblitz-app
- react-admin-dashboard
- Fixed warnings in react-admin-dashboard
> chore: added necessary package-lock files for CI

- examples/kendo-react-finance-portfolio/package-lock.json
- examples/kendo-react-finance-portfolio/package.json
- examples/kendo-react-ssr/package-lock.json
- examples/kendo-react-ssr/package.json
Address the dependabot alerts https://github.com/telerik/kendo-react/security/dependabot
> Security alerts by dependabot

- examples/coffee-warehouse-nextjs/package-lock.json
- examples/coffee-warehouse-nextjs/package.json
- examples/kendo-react-build-a-sales-dashboard/package-lock.json
- examples/kendo-react-build-a-sales-dashboard/package.json
- examples/kendo-react-file-manager/package-lock.json
- examples/kendo-react-file-manager/package.json
- examples/kendo-react-homepage-demo/package-lock.json
- examples/kendo-react-homepage-demo/package.json
- examples/kendo-react-nodejs-express/client/package-lock.json
- examples/kendo-react-nodejs-express/client/package.json
- examples/kendo-react-sales-dashboard/package-lock.json
- examples/kendo-react-sales-dashboard/package.json
- examples/kendo-react-stackblitz-app/package-lock.json
- examples/kendo-react-stackblitz-app/package.json
- examples/react-admin-dashboard/package-lock.json
- examples/react-admin-dashboard/package.json
- examples/react-coffee-warehouse/package-lock.json
- examples/react-coffee-warehouse/package.json
- examples/react-grid-live-data/package-lock.json
- examples/react-grid-live-data/package.json
Address the dapendabot alerts https://github.com/telerik/kendo-react/security/dependabot.
> chore(apps): add overrides in package.json

- .github/workflows/ci.yml
Optimization of the CI: 
- Do not run CI on change in folder https://github.com/telerik/kendo-react/tree/master/knowledge-base
- Do build app if there is no change in its folder.
> chore(CI): build app only on change in the app folder

- .github/workflows/cd.yml
- live/bin/build-gh-pages
This should fix the CD. I tested it here https://github.com/telerik/kendo-react/actions/runs/7630952599
> chore(cd): fix build paths

- knowledge-base/custom-expand-collapse-column.md
- knowledge-base/examples/grid/custom-expand-collapse-column/main.jsx
closes https://github.com/telerik/kendo-react-private/issues/2520
> docs(grid): Updating custom expand-collapse cell KB

- knowledge-base/examples/grid/add-new-column/ColumnForm.jsx
- knowledge-base/examples/grid/add-new-column/main.jsx
- knowledge-base/grid-cell-whitespace-textoverflow.md
closes https://github.com/telerik/kendo-react-private/issues/2503
> docs(grid): Fixing kb articles

- knowledge-base/examples/scheduler/start-end-dates/main.jsx
- knowledge-base/scheduler-get-start-end-values.md
Related to https://github.com/telerik/kendo-react-private/issues/3344
> docs(scheduler): start and end slot dates KB

- knowledge-base/examples/grid/stateful/main.jsx
- knowledge-base/examples/grid/stateful/with-state.jsx
- knowledge-base/grid-stateful.md
Related to https://github.com/telerik/kendo-react-private/issues/3148
Test example: https://stackblitz.com/edit/react-wjahvk-mvt9ef?file=app%2Fwith-state.jsx
> docs(grid): refactor to functional component

- knowledge-base/examples/grid/date-range-filter/main.jsx
- knowledge-base/grid-date-ragne-filter.md
closes https://github.com/telerik/kendo-react-private/issues/2583
Test example: https://stackblitz.com/edit/react-fya4xe-a85zmh?file=app%2Fmain.jsx
> docs:(DatePicker): add defaultValue and format to example

- knowledge-base/examples/grid/grid-row-colors/alternate-colors/main.jsx
- knowledge-base/examples/grid/grid-row-colors/single-row-color/main.jsx
- knowledge-base/grid-alternate-row-colors.md
- knowledge-base/nextjs-theme-switcher.md
- knowledge-base/pdfexport-setup-proxy.md
Related to https://github.com/telerik/kendo-react-private/issues/3762
> KB articles for PDF server proxy, Grid row colors, and Next.js theme switcher

- knowledge-base/editor-double-underilne.md
- knowledge-base/editor-set-default-target-blank.md
- knowledge-base/examples/editor/editor-double-underilne/doubleUnderlineTool.tsx
- knowledge-base/examples/editor/editor-double-underilne/main.tsx
- knowledge-base/examples/editor/editor-set-default-target-blank/content.ts
- knowledge-base/examples/editor/editor-set-default-target-blank/main.tsx
- knowledge-base/examples/editor/editor-set-default-target-blank/schema-utils.ts
- knowledge-base/examples/editor/editor-set-default-target-blank/schema.ts
- knowledge-base/examples/radialgauge/main.tsx
- knowledge-base/radial-gauge-show-value.md
Related to: https://github.com/telerik/kendo-react-private/issues/3814
> April kb articles

- knowledge-base/editor-set-default-target-blank.md
Removing a redundant line in the set default target KB article
> remove redundant ticketid

- knowledge-base/editor-multilevel-list-styles.md
- knowledge-base/examples/editor/editor-multilevel-list-styles/main.jsx
Closes: https://github.com/telerik/kendo-react-private/issues/3815
> add multilevel list styles KB article

- .github/dependabot.yml
Ref: https://github.com/telerik/kendo-react-private/issues/3469
> chore(dependabot): add kbs app

- .github/dependabot.yml
- .github/workflows/ci.yml
- examples/ecommerce-jewellery-store/package-lock.json
- live/bin/build-gh-pages
- live/static/index.html
Implements https://github.com/telerik/kendo-react-private/issues/4817
> chore: add vite sample app to github pages

- examples/ecommerce-jewellery-store/package-lock.json
- examples/ecommerce-jewellery-store/package.json
- examples/ecommerce-jewellery-store/src/App.tsx
- examples/ecommerce-jewellery-store/src/data/items.ts
- examples/ecommerce-jewellery-store/vite.config.ts
Implements https://github.com/telerik/kendo-react-private/issues/4817
> Fix deploy of ecommerce-jewellery-store app

- examples/kendo-react-finance-portfolio/package-lock.json
- examples/kendo-react-finance-portfolio/package.json
Part of https://github.com/telerik/kendo-react-private/issues/4911
> chore(apps): resolve dependabot alerts

- examples/react-coffee-warehouse/public/404.html
- examples/react-coffee-warehouse/public/index.html
Part of: https://github.com/telerik/kendo-react-private/issues/4033
> fix: routing in react-coffee-warehouse

- .github/ISSUE_TEMPLATE/1_bug_report.yml
- .github/ISSUE_TEMPLATE/2_documentation_issue.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/other.md
Implements https://github.com/telerik/kendo-react-private/issues/5018
> chore: add issue template

- examples/coffee-warehouse-nextjs/package.json
- examples/kendo-react-e-commerce-astro-app/package-lock.json
- examples/kendo-react-e-commerce-astro-app/package.json
- examples/kendo-react-file-manager/package-lock.json
- examples/kendo-react-file-manager/package.json
- examples/kendo-react-finance-portfolio/package-lock.json
- examples/kendo-react-finance-portfolio/package.json
- examples/kendo-react-homepage-demo/package-lock.json
- examples/kendo-react-homepage-demo/package.json
- examples/kendo-react-nextjs/package.json
- examples/kendo-unstyled-tailwind/package.json
- examples/react-admin-dashboard/package-lock.json
- examples/react-admin-dashboard/package.json
- examples/react-coffee-warehouse/package-lock.json
- examples/react-coffee-warehouse/package.json
- examples/react-grid-live-data/package-lock.json
- examples/react-grid-live-data/package.json
implements: https://github.com/telerik/kendo-react-private/issues/4999
> Bump sample apps versions to fix dependabot alerts

- NOTICE.txt
Implements https://github.com/telerik/kendo-react-private/issues/5275
> chore: update notice

- examples/kendo-react-freemium/src/components/AppBarComponent.tsx
Part of https://github.com/telerik/kendo-react-private/issues/4734
> chore: fix click on logo

- examples/ecommerce-jewellery-store/package-lock.json
- examples/ecommerce-jewellery-store/package.json
- examples/kendo-react-e-commerce-astro-app/package-lock.json
- examples/kendo-react-e-commerce-astro-app/package.json
- examples/kendo-react-file-manager/package-lock.json
- examples/kendo-react-file-manager/package.json
- examples/kendo-react-finance-portfolio/package-lock.json
- examples/kendo-react-finance-portfolio/package.json
- examples/kendo-react-homepage-demo/package-lock.json
- examples/kendo-react-homepage-demo/package.json
- examples/kendo-react-project-tracker-app/package-lock.json
- examples/kendo-react-project-tracker-app/package.json
- examples/react-admin-dashboard/package-lock.json
- examples/react-admin-dashboard/package.json
- examples/react-coffee-warehouse/package-lock.json
- examples/react-coffee-warehouse/package.json
- examples/react-grid-live-data/package-lock.json
- examples/react-grid-live-data/package.json
Implements: https://github.com/telerik/kendo-react-private/issues/5358
> Fix alerts

- examples/kendo-react-project-tracker-app/src/components/AppBarComponent.tsx
- examples/kendo-react-project-tracker-app/src/components/DrawerComponent.tsx
- examples/kendo-react-project-tracker-app/src/index.css
- examples/kendo-react-project-tracker-app/src/pages/Home.tsx
- examples/kendo-react-project-tracker-app/src/pages/NewTask.tsx
- examples/kendo-react-project-tracker-app/src/pages/Projects.tsx
- examples/kendo-react-project-tracker-app/src/pages/Settings.tsx
- examples/kendo-react-project-tracker-app/src/pages/Task.tsx
- examples/kendo-react-project-tracker-app/src/pages/Tasks.tsx
- examples/kendo-react-project-tracker-app/src/pages/Team.tsx
- examples/kendo-react-project-tracker-app/src/pages/TeamManagement.tsx
- examples/kendo-react-project-tracker-app/src/pages/data.ts
Closes: https://github.com/telerik/kendo-react-private/issues/5604
> A11y fixes

- examples/kendo-react-e-commerce-astro-app/package-lock.json
- examples/kendo-react-e-commerce-astro-app/package.json
implements: https://github.com/telerik/kendo-react-private/issues/5358
> chore: bump vite and esbuid in e-commerce app

- examples/coffee-warehouse-nextjs/package.json
- examples/kendo-react-nextjs/package.json
Part of: https://github.com/telerik/kendo-react-private/issues/5649
> chore(apps): bump next to v14.2.25

- .github/ISSUE_TEMPLATE/1_bug_report.yml
Implements: https://github.com/telerik/kendo-react-private/issues/5680
> chore: edit bug template

- .github/ISSUE_TEMPLATE/1_bug_report.yml
Implements: https://github.com/telerik/kendo-react-private/issues/5680
> chore: remove colon sign

- examples/kendo-react-file-manager/src/components/FileManagerToolbar.tsx
part of https://github.com/telerik/kendo-react-private/issues/5679
> choe: migrate service
